const wordsByLevel = {
  1: [
    { word: "bag", parts: ["B.png", "short-a.png", "G.png"], image: "bag.png" },
    { word: "bat", parts: ["B.png", "short-a.png", "T.png"], image: "bat.png" },
    { word: "cap", parts: ["C.png", "short-a.png", "P.png"], image: "cap.png" },
    { word: "cat", parts: ["C.png", "short-a.png", "T.png"], image: "cat.png" },
    { word: "dad", parts: ["D.png", "short-a.png", "D.png"], image: "dad.png" },
    { word: "fan", parts: ["F.png", "short-a.png", "N.png"], image: "fan.png" },
    { word: "gap", parts: ["G.png", "short-a.png", "P.png"], image: "gap.png" },
    { word: "ham", parts: ["H.png", "short-a.png", "M.png"], image: "ham.png" },
    { word: "jam", parts: ["J.png", "short-a.png", "M.png"], image: "jam.png" },
    { word: "lap", parts: ["L.png", "short-a.png", "P.png"], image: "lap.png" },
    { word: "man", parts: ["M.png", "short-a.png", "N.png"], image: "man.png" },
    { word: "mat", parts: ["M.png", "short-a.png", "T.png"], image: "mat.png" },
    { word: "nap", parts: ["N.png", "short-a.png", "P.png"], image: "nap.png" },
    { word: "pan", parts: ["P.png", "short-a.png", "N.png"], image: "pan.png" },
    { word: "pat", parts: ["P.png", "short-a.png", "T.png"], image: "pat.png" },
    { word: "rag", parts: ["R.png", "short-a.png", "G.png"], image: "rag.png" },
    { word: "rat", parts: ["R.png", "short-a.png", "T.png"], image: "rat.png" },
    { word: "sad", parts: ["S.png", "short-a.png", "D.png"], image: "sad.png" },
    { word: "sat", parts: ["S.png", "short-a.png", "T.png"], image: "sat.png" },
    { word: "tap", parts: ["T.png", "short-a.png", "P.png"], image: "tap.png" },
    { word: "bed", parts: ["B.png", "short-e.png", "D.png"], image: "bed.png" },
    { word: "beg", parts: ["B.png", "short-e.png", "G.png"], image: "beg.png" },
    { word: "den", parts: ["D.png", "short-e.png", "N.png"], image: "den.png" },
    { word: "fed", parts: ["F.png", "short-e.png", "D.png"], image: "fed.png" },
    { word: "gem", parts: ["G.png", "short-e.png", "M.png"], image: "gem.png" },
    { word: "get", parts: ["G.png", "short-e.png", "T.png"], image: "get.png" },
    { word: "hen", parts: ["H.png", "short-e.png", "N.png"], image: "hen.png" },
    { word: "jet", parts: ["J.png", "short-e.png", "T.png"], image: "jet.png" },
    { word: "leg", parts: ["L.png", "short-e.png", "G.png"], image: "leg.png" },
    { word: "men", parts: ["M.png", "short-e.png", "N.png"], image: "men.png" },
    { word: "net", parts: ["N.png", "short-e.png", "T.png"], image: "net.png" },
    { word: "pen", parts: ["P.png", "short-e.png", "N.png"], image: "pen.png" },
    { word: "pet", parts: ["P.png", "short-e.png", "T.png"], image: "pet.png" },
    { word: "red", parts: ["R.png", "short-e.png", "D.png"], image: "red.png" },
    { word: "set", parts: ["S.png", "short-e.png", "T.png"], image: "set.png" },
    { word: "ten", parts: ["T.png", "short-e.png", "N.png"], image: "ten.png" },
    { word: "vet", parts: ["V.png", "short-e.png", "T.png"], image: "vet.png" },
    { word: "web", parts: ["W.png", "short-e.png", "B.png"], image: "web.png" }
  ],
  2: [
    { word: "cake", parts: ["C.png", "long-a.png", "K.png", "magic-E.png"], image: "cake.png" },
    { word: "lake", parts: ["L.png", "long-a.png", "K.png", "magic-E.png"], image: "lake.png" },
    { word: "name", parts: ["N.png", "long-a.png", "M.png", "magic-E.png"], image: "name.png" },
    { word: "tape", parts: ["T.png", "long-a.png", "P.png", "magic-E.png"], image: "tape.png" },
    { word: "game", parts: ["G.png", "long-a.png", "M.png", "magic-E.png"], image: "game.png" },
    { word: "bike", parts: ["B.png", "long-i.png", "K.png", "magic-E.png"], image: "bike.png" },
    { word: "like", parts: ["L.png", "long-i.png", "K.png", "magic-E.png"], image: "like.png" },
    { word: "hide", parts: ["H.png", "long-i.png", "D.png", "magic-E.png"], image: "hide.png" },
    { word: "ride", parts: ["R.png", "long-i.png", "D.png", "magic-E.png"], image: "ride.png" },
    { word: "time", parts: ["T.png", "long-i.png", "M.png", "magic-E.png"], image: "time.png" },
    { word: "note", parts: ["N.png", "long-o.png", "T.png", "magic-E.png"], image: "note.png" },
    { word: "rope", parts: ["R.png", "long-o.png", "P.png", "magic-E.png"], image: "rope.png" },
    { word: "home", parts: ["H.png", "long-o.png", "M.png", "magic-E.png"], image: "home.png" },
    { word: "joke", parts: ["J.png", "long-o.png", "K.png", "magic-E.png"], image: "joke.png" },
    { word: "vote", parts: ["V.png", "long-o.png", "T.png", "magic-E.png"], image: "vote.png" },
    { word: "cube", parts: ["C.png", "long-u.png", "B.png", "magic-E.png"], image: "cube.png" },
    { word: "mule", parts: ["M.png", "long-u.png", "L.png", "magic-E.png"], image: "mule.png" },
    { word: "rude", parts: ["R.png", "long-u.png", "D.png", "magic-E.png"], image: "rude.png" },
    { word: "tube", parts: ["T.png", "long-u.png", "B.png", "magic-E.png"], image: "tube.png" },
    { word: "cute", parts: ["C.png", "long-u.png", "T.png", "magic-E.png"], image: "cute.png" },
    { word: "cage", parts: ["C.png", "long-a.png", "G.png", "magic-E.png"], image: "cage.png" },
    { word: "page", parts: ["P.png", "long-a.png", "G.png", "magic-E.png"], image: "page.png" },
    { word: "dine", parts: ["D.png", "long-i.png", "N.png", "magic-E.png"], image: "dine.png" },
    { word: "pine", parts: ["P.png", "long-i.png", "N.png", "magic-E.png"], image: "pine.png" },
    { word: "bone", parts: ["B.png", "long-o.png", "N.png", "magic-E.png"], image: "bone.png" },
    { word: "cone", parts: ["C.png", "long-o.png", "N.png", "magic-E.png"], image: "cone.png" },
    { word: "mole", parts: ["M.png", "long-o.png", "L.png", "magic-E.png"], image: "mole.png" },
    { word: "pole", parts: ["P.png", "long-o.png", "L.png", "magic-E.png"], image: "pole.png" },
    { word: "fuse", parts: ["F.png", "long-u.png", "S.png", "magic-E.png"], image: "fuse.png" },
    { word: "muse", parts: ["M.png", "long-u.png", "S.png", "magic-E.png"], image: "muse.png" },
    { word: "huge", parts: ["H.png", "long-u.png", "G.png", "magic-E.png"], image: "huge.png" },
    { word: "duke", parts: ["D.png", "long-u.png", "K.png", "magic-E.png"], image: "duke.png" },
    { word: "bake", parts: ["B.png", "long-a.png", "K.png", "magic-E.png"], image: "bake.png" },
    { word: "make", parts: ["M.png", "long-a.png", "K.png", "magic-E.png"], image: "make.png" },
    { word: "fake", parts: ["F.png", "long-a.png", "K.png", "magic-E.png"], image: "fake.png" },
    { word: "rake", parts: ["R.png", "long-a.png", "K.png", "magic-E.png"], image: "rake.png" },
    { word: "take", parts: ["T.png", "long-a.png", "K.png", "magic-E.png"], image: "take.png" },
    { word: "sake", parts: ["S.png", "long-a.png", "K.png", "magic-E.png"], image: "sake.png" },
    { word: "poke", parts: ["P.png", "long-o.png", "K.png", "magic-E.png"], image: "poke.png" },
    { word: "woke", parts: ["W.png", "long-o.png", "K.png", "magic-E.png"], image: "woke.png" }
  ],
  3: [
    { word: "chat", parts: ["CH.png", "short-a.png", "T.png"], image: "chat.png" },
    { word: "ship", parts: ["SH.png", "short-i.png", "P.png"], image: "ship.png" },
    { word: "bath", parts: ["B.png", "short-a.png", "TH.png"], image: "bath.png" },
    { word: "chip", parts: ["CH.png", "short-i.png", "P.png"], image: "chip.png" },
    { word: "math", parts: ["M.png", "short-a.png", "TH.png"], image: "math.png" },
    { word: "path", parts: ["P.png", "short-a.png", "TH.png"], image: "path.png" },
    { word: "thin", parts: ["TH.png", "short-i.png", "N.png"], image: "thin.png" },
    { word: "thud", parts: ["TH.png", "short-u.png", "D.png"], image: "thud.png" },
    { word: "bash", parts: ["B.png", "short-a.png", "SH.png"], image: "bash.png" },
    { word: "wish", parts: ["W.png", "short-i.png", "SH.png"], image: "wish.png" },
    { word: "chop", parts: ["CH.png", "short-o.png", "P.png"], image: "chop.png" },
    { word: "shop", parts: ["SH.png", "short-o.png", "P.png"], image: "shop.png" },
    { word: "that", parts: ["TH.png", "short-a.png", "T.png"], image: "that.png" },
    { word: "then", parts: ["TH.png", "short-e.png", "N.png"], image: "then.png" },
    { word: "chin", parts: ["CH.png", "short-i.png", "N.png"], image: "chin.png" },
    { word: "shed", parts: ["SH.png", "short-e.png", "D.png"], image: "shed.png" },
    { word: "this", parts: ["TH.png", "short-i.png", "S.png"], image: "this.png" },
    { word: "check", parts: ["CH.png", "short-e.png", "CK.png"], image: "check.png" },
    { word: "duck", parts: ["D.png", "short-u.png", "CK.png"], image: "duck.png" },
    { word: "luck", parts: ["L.png", "short-u.png", "CK.png"], image: "luck.png" },
    { word: "dash", parts: ["D.png", "short-a.png", "SH.png"], image: "dash.png" },
    { word: "cash", parts: ["C.png", "short-a.png", "SH.png"], image: "cash.png" },
    { word: "shut", parts: ["SH.png", "short-u.png", "T.png"], image: "shut.png" },
    { word: "them", parts: ["TH.png", "short-e.png", "M.png"], image: "them.png" },
    { word: "dish", parts: ["D.png", "short-i.png", "SH.png"], image: "dish.png" },
    { word: "fish", parts: ["F.png", "short-i.png", "SH.png"], image: "fish.png" },
    { word: "mash", parts: ["M.png", "short-a.png", "SH.png"], image: "mash.png" },
    { word: "shun", parts: ["SH.png", "short-u.png", "N.png"], image: "shun.png" },
    { word: "sing", parts: ["S.png", "short-i.png", "NG.png"], image: "sing.png" },
    { word: "long", parts: ["L.png", "short-o.png", "NG.png"], image: "long.png" },
    { word: "king", parts: ["K.png", "short-i.png", "NG.png"], image: "king.png" },
    { word: "ring", parts: ["R.png", "short-i.png", "NG.png"], image: "ring.png" },
    { word: "wing", parts: ["W.png", "short-i.png", "NG.png"], image: "wing.png" },
    { word: "song", parts: ["S.png", "short-o.png", "NG.png"], image: "song.png" },
    { word: "lung", parts: ["L.png", "short-u.png", "NG.png"], image: "lung.png" },
    { word: "bang", parts: ["B.png", "short-a.png", "NG.png"], image: "bang.png" },
    { word: "hang", parts: ["H.png", "short-a.png", "NG.png"], image: "hang.png" },
    { word: "fang", parts: ["F.png", "short-a.png", "NG.png"], image: "fang.png" },
    { word: "hush", parts: ["H.png", "short-u.png", "SH.png"], image: "hush.png" },
    { word: "song", parts: ["S.png", "short-o.png", "NG.png"], image: "song.png" }
  ]
};
