const wordLevels = {
 1: [
    { word: "bag", parts: ["B.png", "short-a.png", "G.png"], image: "bag.png" },
    { word: "bat", parts: ["B.png", "short-a.png", "T.png"], image: "bat.png" },
    { word: "cap", parts: ["C.png", "short-a.png", "P.png"], image: "cap.png" },
    { word: "cat", parts: ["C.png", "short-a.png", "T.png"], image: "cat.png" },
    { word: "dad", parts: ["D.png", "short-a.png", "D.png"], image: "dad.png" },
    { word: "fan", parts: ["F.png", "short-a.png", "N.png"], image: "fan.png" },
    { word: "gap", parts: ["G.png", "short-a.png", "P.png"], image: "gap.png" },
    { word: "ham", parts: ["H.png", "short-a.png", "M.png"], image: "ham.png" },
    { word: "jam", parts: ["J.png", "short-a.png", "M.png"], image: "jam.png" },
    { word: "lap", parts: ["L.png", "short-a.png", "P.png"], image: "lap.png" },
    { word: "man", parts: ["M.png", "short-a.png", "N.png"], image: "man.png" },
    { word: "mat", parts: ["M.png", "short-a.png", "T.png"], image: "mat.png" },
    { word: "nap", parts: ["N.png", "short-a.png", "P.png"], image: "nap.png" },
    { word: "pan", parts: ["P.png", "short-a.png", "N.png"], image: "pan.png" },
    { word: "pat", parts: ["P.png", "short-a.png", "T.png"], image: "pat.png" },
    { word: "rag", parts: ["R.png", "short-a.png", "G.png"], image: "rag.png" },
    { word: "rat", parts: ["R.png", "short-a.png", "T.png"], image: "rat.png" },
    { word: "sad", parts: ["S.png", "short-a.png", "D.png"], image: "sad.png" },
    { word: "sat", parts: ["S.png", "short-a.png", "T.png"], image: "sat.png" },
    { word: "tap", parts: ["T.png", "short-a.png", "P.png"], image: "tap.png" },
    { word: "bed", parts: ["B.png", "short-e.png", "D.png"], image: "bed.png" },
    { word: "beg", parts: ["B.png", "short-e.png", "G.png"], image: "beg.png" },
    { word: "den", parts: ["D.png", "short-e.png", "N.png"], image: "den.png" },
    { word: "fed", parts: ["F.png", "short-e.png", "D.png"], image: "fed.png" },
    { word: "gem", parts: ["G.png", "short-e.png", "M.png"], image: "gem.png" },
    { word: "get", parts: ["G.png", "short-e.png", "T.png"], image: "get.png" },
    { word: "hen", parts: ["H.png", "short-e.png", "N.png"], image: "hen.png" },
    { word: "jet", parts: ["J.png", "short-e.png", "T.png"], image: "jet.png" },
    { word: "leg", parts: ["L.png", "short-e.png", "G.png"], image: "leg.png" },
    { word: "men", parts: ["M.png", "short-e.png", "N.png"], image: "men.png" },
    { word: "net", parts: ["N.png", "short-e.png", "T.png"], image: "net.png" },
    { word: "pen", parts: ["P.png", "short-e.png", "N.png"], image: "pen.png" },
    { word: "pet", parts: ["P.png", "short-e.png", "T.png"], image: "pet.png" },
    { word: "red", parts: ["R.png", "short-e.png", "D.png"], image: "red.png" },
    { word: "set", parts: ["S.png", "short-e.png", "T.png"], image: "set.png" },
    { word: "ten", parts: ["T.png", "short-e.png", "N.png"], image: "ten.png" },
    { word: "vet", parts: ["V.png", "short-e.png", "T.png"], image: "vet.png" },
    { word: "web", parts: ["W.png", "short-e.png", "B.png"], image: "web.png" },
    { word: "wet", parts: ["W.png", "short-e.png", "T.png"], image: "wet.png" },
    { word: "yes", parts: ["Y.png", "short-e.png", "S.png"], image: "yes.png" },
    { word: "bib", parts: ["B.png", "short-i.png", "B.png"], image: "bib.png" },
    { word: "big", parts: ["B.png", "short-i.png", "G.png"], image: "big.png" },
    { word: "bin", parts: ["B.png", "short-i.png", "N.png"], image: "bin.png" },
    { word: "bit", parts: ["B.png", "short-i.png", "T.png"], image: "bit.png" },
    { word: "dig", parts: ["D.png", "short-i.png", "G.png"], image: "dig.png" },
    { word: "dip", parts: ["D.png", "short-i.png", "P.png"], image: "dip.png" },
    { word: "fig", parts: ["F.png", "short-i.png", "G.png"], image: "fig.png" },
    { word: "fin", parts: ["F.png", "short-i.png", "N.png"], image: "fin.png" },
    { word: "fit", parts: ["F.png", "short-i.png", "T.png"], image: "fit.png" },
    { word: "gig", parts: ["G.png", "short-i.png", "G.png"], image: "gig.png" },
    { word: "him", parts: ["H.png", "short-i.png", "M.png"], image: "him.png" },
    { word: "hip", parts: ["H.png", "short-i.png", "P.png"], image: "hip.png" },
    { word: "kid", parts: ["K.png", "short-i.png", "D.png"], image: "kid.png" },
    { word: "lid", parts: ["L.png", "short-i.png", "D.png"], image: "lid.png" },
    { word: "lip", parts: ["L.png", "short-i.png", "P.png"], image: "lip.png" },
    { word: "pig", parts: ["P.png", "short-i.png", "G.png"], image: "pig.png" },
    { word: "pin", parts: ["P.png", "short-i.png", "N.png"], image: "pin.png" },
    { word: "pit", parts: ["P.png", "short-i.png", "T.png"], image: "pit.png" },
    { word: "sit", parts: ["S.png", "short-i.png", "T.png"], image: "sit.png" },
    { word: "wig", parts: ["W.png", "short-i.png", "G.png"], image: "wig.png" },
    // Remaining ~40 to reach 100 entries
  ],

2: [
    // 70 Magic-E words
    { word: "bake", parts: ["B.png", "long-a.png", "K.png", "magic-E.png"], image: "bake.png" },
    { word: "cage", parts: ["C.png", "long-a.png", "G.png", "magic-E.png"], image: "cage.png" },
    { word: "case", parts: ["C.png", "long-a.png", "S.png", "magic-E.png"], image: "case.png" },
    { word: "cave", parts: ["C.png", "long-a.png", "V.png", "magic-E.png"], image: "cave.png" },
    { word: "fame", parts: ["F.png", "long-a.png", "M.png", "magic-E.png"], image: "fame.png" },
    { word: "game", parts: ["G.png", "long-a.png", "M.png", "magic-E.png"], image: "game.png" },
    { word: "gate", parts: ["G.png", "long-a.png", "T.png", "magic-E.png"], image: "gate.png" },
    { word: "lake", parts: ["L.png", "long-a.png", "K.png", "magic-E.png"], image: "lake.png" },
    { word: "made", parts: ["M.png", "long-a.png", "D.png", "magic-E.png"], image: "made.png" },
    { word: "name", parts: ["N.png", "long-a.png", "M.png", "magic-E.png"], image: "name.png" },
    { word: "page", parts: ["P.png", "long-a.png", "G.png", "magic-E.png"], image: "page.png" },
    { word: "pale", parts: ["P.png", "long-a.png", "L.png", "magic-E.png"], image: "pale.png" },
    { word: "race", parts: ["R.png", "long-a.png", "C.png", "magic-E.png"], image: "race.png" },
    { word: "safe", parts: ["S.png", "long-a.png", "F.png", "magic-E.png"], image: "safe.png" },
    { word: "same", parts: ["S.png", "long-a.png", "M.png", "magic-E.png"], image: "same.png" },
    { word: "tape", parts: ["T.png", "long-a.png", "P.png", "magic-E.png"], image: "tape.png" },
    { word: "tale", parts: ["T.png", "long-a.png", "L.png", "magic-E.png"], image: "tale.png" },
    { word: "vane", parts: ["V.png", "long-a.png", "N.png", "magic-E.png"], image: "vane.png" },
    { word: "wave", parts: ["W.png", "long-a.png", "V.png", "magic-E.png"], image: "wave.png" },
    { word: "wage", parts: ["W.png", "long-a.png", "G.png", "magic-E.png"], image: "wage.png" },
    { word: "bike", parts: ["B.png", "long-i.png", "K.png", "magic-E.png"], image: "bike.png" },
    { word: "dime", parts: ["D.png", "long-i.png", "M.png", "magic-E.png"], image: "dime.png" },
    { word: "fine", parts: ["F.png", "long-i.png", "N.png", "magic-E.png"], image: "fine.png" },
    { word: "hide", parts: ["H.png", "long-i.png", "D.png", "magic-E.png"], image: "hide.png" },
    { word: "kite", parts: ["K.png", "long-i.png", "T.png", "magic-E.png"], image: "kite.png" },
    { word: "like", parts: ["L.png", "long-i.png", "K.png", "magic-E.png"], image: "like.png" },
    { word: "mine", parts: ["M.png", "long-i.png", "N.png", "magic-E.png"], image: "mine.png" },
    { word: "ride", parts: ["R.png", "long-i.png", "D.png", "magic-E.png"], image: "ride.png" },
    { word: "time", parts: ["T.png", "long-i.png", "M.png", "magic-E.png"], image: "time.png" },
    { word: "vine", parts: ["V.png", "long-i.png", "N.png", "magic-E.png"], image: "vine.png" },
    // ...add more magic-e words as needed

    // 30 review words from level 1
    { word: "cap", parts: ["C.png", "short-a.png", "P.png"], image: "cap.png" },
    { word: "dog", parts: ["D.png", "short-o.png", "G.png"], image: "dog.png" },
    { word: "jet", parts: ["J.png", "short-e.png", "T.png"], image: "jet.png" },
    { word: "lip", parts: ["L.png", "short-i.png", "P.png"], image: "lip.png" },
    { word: "mud", parts: ["M.png", "short-u.png", "D.png"], image: "mud.png" },
    { word: "pan", parts: ["P.png", "short-a.png", "N.png"], image: "pan.png" },
    { word: "pen", parts: ["P.png", "short-e.png", "N.png"], image: "pen.png" },
    { word: "bib", parts: ["B.png", "short-i.png", "B.png"], image: "bib.png" },
    { word: "mop", parts: ["M.png", "short-o.png", "P.png"], image: "mop.png" },
    { word: "cup", parts: ["C.png", "short-u.png", "P.png"], image: "cup.png" }
  ]
};
